# Generated by Django 5.0.8 on 2024-08-08 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
    ]
